### ISSUE TITLE
Discord footer link goes to archived channel

### ISSUE THREAD

**Issue by br41nslug** [directus/website#118]
The "Communiy Chat" link in the footer of directus.io is pointing to a channel thats since been archived.

Link: https://discord.com/channels/725371605378924594/1019641731332976722

![image](https://github.com/directus/directus/assets/9389634/b043c7c4-b5c2-4f35-abd1-32d15a060afb)

**Comment by bryantgillespie** [comment]
I got you. Building now!

**Comment by phazonoverload** [comment]
This handled @bryantgillespie ?

**Comment by bryantgillespie** [comment]
Yup resolved.
