### ISSUE TITLE
Banner overflow on smaller mobile devices

### ISSUE THREAD

**Issue by paescuj** [directus/website#133]
For example with Galaxy S20 devices

<img width="440" src="https://github.com/directus/website/assets/5363448/e7857ddc-6a81-4139-a5cc-63a9a2c2af3b">
<img width="440" src="https://github.com/directus/website/assets/5363448/ac46b470-d630-4246-9560-abb5e337cbc5">

**Comment by alexchopin** [comment]
https://linear.app/directus/issue/WEB-211/banner-overflow-on-smaller-mobile-devices
