### ISSUE TITLE
Tooltip on the pricing page doesn't open on mobile (iOS) 

### ISSUE THREAD

**Issue by VincentKempers** [directus/website#136]
One of our users noted that the tool tip doesn't work on the pricing page on mobile (iOS).
It doesn't open but you can see that the icon is active when you click on it.

This is being run in the chrome browser on ios.
![image](https://github.com/directus/website/assets/14160793/251d05c4-e2f7-487d-9881-b9f3f8e5aca8)

Tested it on safari and same issue only way I could trigger it is on hold but it will also think I'm copying a text.
https://github.com/directus/website/assets/14160793/e221cbf1-4fdf-446a-a444-4006a64ef5c1

**Comment by alexchopin** [comment]
https://linear.app/directus/issue/WEB-212/tooltip-on-the-pricing-page-doesnt-open-on-mobile-ios
