### ISSUE TITLE
Episode pages > Move Resources to tab

### ISSUE THREAD

**Issue by bryantgillespie** [directus/website#150]
![ScreenShot 2024-03-29 at 11 33 25@2x](https://github.com/directus/website/assets/23302570/db166169-9c1d-4ce6-904d-846df783f745)

**Todo**
- Shift resources from meta sidebar to tab

**Maybe**
Show Resource as unfurled link card instead of just links
![ScreenShot 2024-03-29 at 11 34 49@2x](https://github.com/directus/website/assets/23302570/4e9035fa-5381-491e-a638-4f15a39f6104)

**Comment by alexchopin** [comment]
https://linear.app/directus/issue/WEB-213/episode-pages-move-resources-to-tab
