### ISSUE TITLE
Modal doesn't work in FireFox

### ISSUE THREAD

**Issue by benhaynes** [directus/website#2]
https://twitter.com/sprtnturtle/status/1058025879828258817

**Comment by rijkvanzanten** [comment]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/9141017/47929762-71317380-dea0-11e8-91a2-ed183d324266.png">

Waiting for more info to reproduce on Twitter: 
https://twitter.com/rijkvanzanten/status/1058405984991961089

**Comment by benhaynes** [comment]
Fixed by: https://github.com/directus/website/commit/95b672e89ec2cdcf76557c18e84e29397f0f5eaa
