### ISSUE TITLE
Can't navigate away from 404 page

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/website#74]
For some reason, none of the JS-routing works on the 404 page. I think it's because Nuxt's error state isn't cleared on navigation or something along those lines.

Ref: https://discord.com/channels/725371605378924594/1115907787835326525/1153547500817481749

https://github.com/directus/website/assets/26413686/3f7cf32d-0c3a-4679-92dc-e6b8dde237cd

Details moved from Linear MARK-1658.

**Comment by bryantgillespie** [comment]
Closed in #141
